version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_MANAGER_URL=${VITE_MANAGER_URL}
        - VITE_CLIENT_URL=${VITE_CLIENT_URL}
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - PORT=${CLIENT_PORT}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_MANAGER_URL=${VITE_MANAGER_URL}
      - VITE_CLIENT_URL=${VITE_CLIENT_URL}
      - NODE_ENV=production

  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_MANAGER_URL=${VITE_MANAGER_URL}
        - VITE_CLIENT_URL=${VITE_CLIENT_URL}
    ports:
      - "${MANAGER_PORT}:3001"
    environment:
      - PORT=${MANAGER_PORT}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_CLIENT_URL=${VITE_CLIENT_URL}
      - VITE_MANAGER_URL=${VITE_MANAGER_URL}
      - NODE_ENV=production

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:${BACKEND_PORT}
      - MANAGER_URL=${VITE_MANAGER_URL}
      - CLIENT_URL=${VITE_CLIENT_URL}
      - ConnectionStrings__Default=Host=db;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - manager
      - backend

volumes:
  pgdata:
