version: "3.9"
services:
  # Client FE service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_MANAGER_URL=${VITE_MANAGER_URL}
        - VITE_CLIENT_URL=${VITE_CLIENT_URL}
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - PORT=${CLIENT_PORT}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_MANAGER_URL=${VITE_MANAGER_URL}
      - VITE_CLIENT_URL=${VITE_CLIENT_URL}
      - NODE_ENV=production

  # Manager FE service
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_MANAGER_URL=${VITE_MANAGER_URL}
        - VITE_CLIENT_URL=${VITE_CLIENT_URL}
    ports:
      - "${MANAGER_PORT}:3001"
    environment:
      - PORT=${MANAGER_PORT}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_CLIENT_URL=${VITE_CLIENT_URL}
      - VITE_MANAGER_URL=${VITE_MANAGER_URL}
      - NODE_ENV=production

  # Backend API service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:${BACKEND_PORT}
      - MANAGER_URL=${VITE_MANAGER_URL}
      - CLIENT_URL=${VITE_CLIENT_URL}
      - ConnectionStrings__DefaultConnection=Host=db;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}

  # PostgreSQL database
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Adminer for database management
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  # Nginx as a reverse proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - manager
      - backend

volumes:
  pgdata:
